configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal
  matrix:

    # MSVC x86
    - arch:       win32
      bitsize:    x86
      platform:   x86
      qt:         5.6\msvc2013
      suffix:     msvc2013
      generator:  "Visual Studio 2013"
      PYTHON: "C:\\Python35"
      PLATFORM_: "x86"

    # MSVC x64
    - arch:       win32
      bitsize:    x64
      platform:   amd64
      qt:         5.6\msvc2013_64
      suffix:     msvc2013
      generator:  "Visual Studio 2013 Win64"
      PYTHON: "C:\\Python35"
      PLATFORM_: "amd64"

install:
  - set PYTHON3="%PYTHON%\python.exe"
  - set UseEnv=true
  - "%PYTHON3% -m pip freeze > requirements.txt"
  - "%PYTHON3% -m pip install -r requirements.txt"
  - "%PYTHON3% -m pip install setuptools"
  - "%PYTHON3% -m pip install virtualenvwrapper"
  - "%PYTHON3% -m pip install --upgrade google-api-python-client"
  - "%PYTHON3% -m pip install --upgrade meson"
  - "%PYTHON3%  -V"
  - call curl.exe -fsSLO https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip
  - call 7z.exe x -oninja ninja-win.zip
  - set QTDIR=C:\Qt\%qt%
  - set PATH=%PATH%;%QTDIR%;%QTDIR%\bin;C:\MinGW\bin;%PYTHON%\Scripts;%APPVEYOR_BUILD_FOLDER%\ninja

before_build:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM_%
  - meson --prefix "%APPVEYOR_BUILD_FOLDER%\install" --buildtype release build
  - echo %PLATFORM_%

build_script:
  - ninja -C build

after_build:
  - ninja -C build install
  - cd install
  - if %PLATFORM_%==x86 (
    echo "-----Deploying 32 Bit Version-----" &
    dir /s &
    md bin\plugins\ &
    echo "Copying ffmpeg plugin" &
    call curl.exe -o bin\plugins\ffmpeg-3.2.4-win32-static.zip "http://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.2.4-win32-static.zip" &
    call 7z.exe x bin\plugins\ffmpeg-3.2.4-win32-static.zip -o"bin\plugins" &
    echo "move ffmpeg.exe and delete ffmpeg leftovers" &
    del bin\plugins\ffmpeg-3.2.4-win32-static.zip &
    move bin\plugins\ffmpeg-3.2.4-win32-static\bin\ffmpeg.exe bin\plugins &
    rmdir /q /s bin\plugins\ffmpeg-3.2.4-win32-static &
    echo "copying qt libraries" &
    windeployqt bin\Pencil2D.exe &
    echo "zipping" &
    Rename bin Pencil2D &
    call 7z.exe a "pencil2d-win32-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" Pencil2D\ &
    echo "zipping done" &
    echo "what's inside?" &
    call 7z.exe l "pencil2d-win32-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    echo "deploying to google drive" &
    cd %APPVEYOR_BUILD_FOLDER%\util &
    call %PYTHON%\\python.exe nightly-build-upload.py "%WIN32_NIGHTLY_PARENT%" "%APPVEYOR_BUILD_FOLDER%\install\pencil2d-win32-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    echo "32 Bit deployed" )

  - if %PLATFORM_%==amd64 (
    echo "----- Deploying 64 Bit Version -----" &
    echo "rename and zip folder" &
    dir /s &
    md bin\plugins\ &
    echo "Copying ffmpeg plugin" &
    call curl.exe -o bin\plugins\ffmpeg-3.2.4-win64-static.zip "http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.2.4-win64-static.zip" &
    call 7z.exe x bin\plugins\ffmpeg-3.2.4-win64-static.zip -o"bin\plugins" &
    echo "move ffmpeg.exe and delete ffmpeg leftovers" &
    del bin\plugins\ffmpeg-3.2.4-win64-static.zip &
    move bin\plugins\ffmpeg-3.2.4-win64-static\bin\ffmpeg.exe bin\plugins &
    rmdir /q /s bin\plugins\ffmpeg-3.2.4-win64-static &
    echo "copying qt libraries" &
    windeployqt bin\Pencil2D.exe &
    echo "zipping" &
    Rename bin Pencil2D &
    call 7z.exe a "pencil2d-win64-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" Pencil2D\ &
    echo "zipping done" &
    echo "what's inside?" &
    call 7z.exe l "pencil2d-win64-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    echo "deploying to google drive" &
    cd %APPVEYOR_BUILD_FOLDER%\util &
    call %PYTHON%\\python.exe nightly-build-upload.py "%WIN64_NIGHTLY_PARENT%" "%APPVEYOR_BUILD_FOLDER%\install\pencil2d-win64-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    echo "64 Bit Deployed" )
